# Generated by Django 3.1.2 on 2020-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('card_id', models.CharField(blank=True, default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'Carpenter',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='CurrentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'CurrentOrder',
            },
        ),
        migrations.CreateModel(
            name='Electrician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('card_id', models.CharField(blank=True, default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'Electrician',
            },
        ),
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('card_id', models.CharField(blank=True, default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'Haircut',
            },
        ),
        migrations.CreateModel(
            name='HouseCleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('card_id', models.CharField(blank=True, default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'houseCleaning',
            },
        ),
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('card_id', models.CharField(blank=True, default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'Painter',
            },
        ),
        migrations.CreateModel(
            name='PestControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('card_id', models.CharField(blank=True, default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'pestConrol',
            },
        ),
        migrations.CreateModel(
            name='Plumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('card_id', models.CharField(blank=True, default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'Plumber',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50)),
                ('card_id', models.CharField(blank=True, default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'Salon',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_heading', models.CharField(max_length=50)),
                ('service_desc', models.TextField()),
                ('service_icon', models.ImageField(upload_to='home/static/img/service_icons')),
                ('card_heading', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
